"""new fields in user model

Revision ID: 8943a88e7772
Revises: c1dc43740e2f
Create Date: 2026-02-20 15:41:20.425612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8943a88e7772'
down_revision = 'c1dc43740e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.alter_column('about_me',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=140),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('about_me',
               existing_type=sa.String(length=140),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
